### ISSUE TITLE
"Error Loading Plugin" after adding the example accessory to the config

### ISSUE THREAD

**Issue by atrus05** [frli4797/homebridge-sector#5]
I have added your full example, change the email, password and panel code. After removing the inline comments I then hit Save. But the log is filling up with the below errors.
```
[2018-11-21 21:43:43] ====================
[2018-11-21 21:43:43] ERROR LOADING PLUGIN homebridge-sector:
[2018-11-21 21:43:43] Error: Cannot find module 'polling-to-event'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-sector/index.js:3:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:23)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:149:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:141:22)
[2018-11-21 21:43:43] ====================
[2018-11-21 21:43:43] Loaded plugin: homebridge-config-ui-x
[2018-11-21 21:43:43] Registering platform 'homebridge-config-ui-x.config'
[2018-11-21 21:43:43] ---
[2018-11-21 21:43:43] Loading 4 platforms...
[2018-11-21 21:43:43] [LiFx] Initializing LifxLan platform...
[2018-11-21 21:43:43] [Harmony Hub] Initializing HarmonyHub platform...
[2018-11-21 21:43:43] [homebridge-plex-sensors.Plex] Initializing homebridge-plex-sensors.Plex platform...
[2018-11-21 21:43:43] [Ringklocka] Initializing ring-video-doorbell platform...
[2018-11-21 21:43:43] Loading 2 accessories...
[2018-11-21 21:43:43] [Agaton Sax] Initializing HomebridgeAutomower accessory...
[2018-11-21 21:43:43] [Agaton Sax] myAutoMower
[2018-11-21 21:43:43] [Agaton Sax] authenticate
[2018-11-21 21:43:43] [Agaton Sax] getServices

/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
            ^
Error: The requested accessory 'Sector-SecuritySystem' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by frli4797** [comment]
Seems like this dependency is in the package.json. One of these things that you discover when installing stuff on anything else than your usual dev laptop.

**Comment by atrus05** [comment]
> Stupid question: you did install the sector plugin?
> 
> `npm -g install homebridge-sector`

Now I am stumped. What did that command do? Is that a separate application/package/thingymabob compared to the one in the homebridge UI interface? Cause I entered the interface, clicked Plugins, searched for homebridge-sector, and that did not work yesterday.
But today, after running your command, not seeing a new plugin in the UI, and THEN searching for homebridge-sector and installing it from the UI... then it worked. Now I am baffled. Are they two different beasts?

**Comment by frli4797** [comment]
`npm -g install homebridge-sector` installs the plugin from command line. The `-g` means globally, that is, not specifically for any one user. 

I don't know whether or not you've installed your homebridge with that flag or not. Regardless, I don't really trust that UI 100% as doesn't seem to install all dependencies for the plugins.

It shouldn't actually behave like that. But the discrepancy in behaviour could strive from the fact that some plugins or homebridge itself where installed without the flag. 

I'm sorry that I don't have a lot of time supporting individual user. If someone decides to contribute to the code, then I'll focus more on making this plugin usable for others than myself.
